version: '3.9'

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
  
  php:
    image: php:7.4-fpm-alpine